services:
    dtc_queue.grid.source.job:
        class: Dtc\QueueBundle\Grid\JobGridSource
        arguments:
            - '@dtc_queue.job_manager.mongodb'
        tags: [{ name: dtc_grid.source }]
        calls: [[autoDiscoverColumns]]
#        calls: [[setColumns, ['@dtc_queue.grid.source.job.columns']]]
    dtc_queue.grid.source.job.columns:
        class: Dtc\QueueBundle\Grid\JobColumns
        arguments: ['@twig']
