services:
    dtc_queue.document_manager:
        synthetic: true

    dtc_queue.entity_manager:
        synthetic: true

    dtc_queue.job_manager.mongodb:
        class: Dtc\QueueBundle\ODM\JobManager
        arguments:
            - '@dtc_queue.document_manager'
            - '%dtc_queue.class_job%'
            - '%dtc_queue.class_job_archive%'
            - '%dtc_queue.class_run%'
            - '%dtc_queue.class_run_archive%'

    dtc_queue.job_manager.beanstalkd:
        class: Dtc\QueueBundle\Beanstalkd\JobManager
        arguments:
            - '%dtc_queue.class_job%'

    dtc_queue.job_manager.rabbit_mq:
        class: Dtc\QueueBundle\RabbitMQ\JobManager

    dtc_queue.job_manager.orm:
        class: Dtc\QueueBundle\ORM\JobManager
        arguments:
            - '@dtc_queue.entity_manager'
            - '%dtc_queue.class_job%'
            - '%dtc_queue.class_job_archive%'
            - '%dtc_queue.class_run%'
            - '%dtc_queue.class_run_archive%'

    dtc_queue.worker_manager:
        class: Dtc\QueueBundle\Model\WorkerManager
        arguments:
            - '@dtc_queue.job_manager'
            - '@dtc_queue.event_dispatcher'
            - '@logger='
        tags: [{ name: monolog.logger, channel: dtc_queue }]

    dtc_queue.event_dispatcher:
        class: Dtc\QueueBundle\EventDispatcher\EventDispatcher
    dtc_queue.remove_listener:
        class: Dtc\QueueBundle\Doctrine\DtcQueueListener
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_listener, event: preRemove }
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine_mongodb.odm.event_listener, event: preRemove }
            - { name: doctrine_mongodb.odm.event_listener, event: perPersist }
            - { name: doctrine_mongodb.odm.event_listener, event: preUpdate }