services:
    dtc_queue.document_manager:
        synthetic: true

    dtc_queue.entity_manager:
        synthetic: true

    dtc_queue.job_manager:
        synthetic: true

    dtc_queue.run_manager:
        synthetic: true

    dtc_queue.job_timing_manager:
        synthetic: true

    dtc_queue.run_manager.mongodb: # deprecated, remove in 4.0
        public: true
        alias: dtc_queue.run_manager.odm

    dtc_queue.run_manager.odm:
        public: true
        class: Dtc\QueueBundle\ODM\RunManager
        arguments:
            - "@dtc_queue.document_manager"
            - "%dtc_queue.class_run%"
            - "%dtc_queue.class_run_archive%"

    dtc_queue.job_timing_manager.odm:
        public: true
        class: Dtc\QueueBundle\ODM\JobTimingManager
        arguments:
            - "@dtc_queue.document_manager"
            - "%dtc_queue.class_job_timing%"
            - "%dtc_queue.record_timings%"

    dtc_queue.grid_source.live_jobs.odm:
        public: true
        class: Dtc\QueueBundle\ODM\LiveJobGridSource
        arguments:
            - "@dtc_queue.job_manager.odm"
        calls:
            - [ 'setAnnotationReader', ['@annotation_reader' ]]
            - [ 'setCacheDir', ['%kernel.cache_dir%' ]]

    dtc_queue.grid_source.live_jobs.orm:
        public: true
        class: Dtc\QueueBundle\ORM\LiveJobGridSource
        arguments:
            - "@dtc_queue.job_manager.orm"
        calls:
            - [ 'setAnnotationReader', ['@annotation_reader' ]]
            - [ 'setCacheDir', ['%kernel.cache_dir%' ]]

    dtc_queue.job_manager.mongodb: # deprecated, remove in 4.0
        alias: dtc_queue.job_manager.odm

    dtc_queue.job_manager.odm:
        public: true
        class: Dtc\QueueBundle\ODM\JobManager
        arguments:
            - "@dtc_queue.run_manager"
            - "@dtc_queue.job_timing_manager"
            - '@dtc_queue.document_manager'
            - '%dtc_queue.class_job%'
            - '%dtc_queue.class_job_archive%'
        calls:
            - ["setMaxPriority", ['%dtc_queue.priority_max%']]
            - ["setPriorityDirection", ['%dtc_queue.priority_direction%']]

    dtc_queue.job_manager.beanstalkd:
        public: true
        class: Dtc\QueueBundle\Beanstalkd\JobManager
        arguments:
            - "@dtc_queue.run_manager"
            - "@dtc_queue.job_timing_manager"
            - '%dtc_queue.class_job%'

    dtc_queue.job_manager.rabbit_mq:
        public: true
        class: Dtc\QueueBundle\RabbitMQ\JobManager
        arguments:
            - "@dtc_queue.run_manager"
            - "@dtc_queue.job_timing_manager"
            - "%dtc_queue.class_job%"
        calls:
            - ["setMaxPriority", ['%dtc_queue.priority_max%']]
            - ["setPriorityDirection", ['%dtc_queue.priority_direction%']]

    dtc_queue.run_manager.orm:
        public: true
        class: Dtc\QueueBundle\ORM\RunManager
        arguments:
            - '@dtc_queue.entity_manager'
            - "%dtc_queue.class_run%"
            - "%dtc_queue.class_run_archive%"

    dtc_queue.job_timing_manager.orm:
        public: true
        class: Dtc\QueueBundle\ORM\JobTimingManager
        arguments:
            - "@dtc_queue.entity_manager"
            - "%dtc_queue.class_job_timing%"
            - "%dtc_queue.record_timings%"

    dtc_queue.run_manager.beanstalkd:
        public: true
        alias: dtc_queue.run_manager_base

    dtc_queue.run_manager.rabbit_mq:
        public: true
        alias: dtc_queue.run_manager_base

    dtc_queue.job_timing_manager.beanstalkd:
        public: true
        alias: dtc_queue.job_timing_manager_base

    dtc_queue.job_timing_manager.rabbit_mq:
        public: true
        alias: dtc_queue.job_timing_manager_base

    dtc_queue.run_manager_base:
        public: true
        class: Dtc\QueueBundle\Model\RunManager
        arguments:
            - "%dtc_queue.class_run%"

    dtc_queue.job_timing_manager_base:
        public: true
        class: Dtc\QueueBundle\Model\JobTimingManager
        arguments:
            - "%dtc_queue.class_job_timing%"
            - "%dtc_queue.record_timings%"

    dtc_queue.job_manager.orm:
        public: true
        class: Dtc\QueueBundle\ORM\JobManager
        arguments:
            - "@dtc_queue.run_manager"
            - "@dtc_queue.job_timing_manager"
            - '@dtc_queue.entity_manager'
            - '%dtc_queue.class_job%'
            - '%dtc_queue.class_job_archive%'
        calls:
            - ["setMaxPriority", ['%dtc_queue.priority_max%']]
            - ["setPriorityDirection", ['%dtc_queue.priority_direction%']]

    dtc_queue.worker_manager:
        public: true
        class: Dtc\QueueBundle\Model\WorkerManager
        arguments:
            - '@dtc_queue.job_manager'
            - '@dtc_queue.event_dispatcher'
        calls:
            - [ "setLogger", ['@?logger'] ]
        tags: [{ name: monolog.logger, channel: dtc_queue }]

    dtc_queue.event_dispatcher:
        public: true
        class: Dtc\QueueBundle\EventDispatcher\EventDispatcher

    dtc_queue.remove_listener:
        public: true
        class: Dtc\QueueBundle\Doctrine\DtcQueueListener
        arguments:
            - '%dtc_queue.class_job_archive%'
            - '%dtc_queue.class_run_archive%'
        tags:
            - { name: doctrine.event_listener, event: preRemove }
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine_mongodb.odm.event_listener, event: preRemove }
            - { name: doctrine_mongodb.odm.event_listener, event: perPersist }
            - { name: doctrine_mongodb.odm.event_listener, event: preUpdate }

    dtc_queue.run.loop:
        public: true
        class: Dtc\QueueBundle\Run\Loop
        arguments:
            - "@dtc_queue.worker_manager"
            - "@dtc_queue.job_manager"
            - "@dtc_queue.run_manager"
        calls:
            - [ "setLogger", ['@?logger'] ]
        tags: [{ name: monolog.logger, channel: dtc_queue }]

    dtc_queue.command.count:
        class: Dtc\QueueBundle\Command\CountCommand
        tags:
            - { name: console.command }

    dtc_queue.command.create_job:
        class: Dtc\QueueBundle\Command\CreateJobCommand
        tags:
            - { name: console.command }

    dtc_queue.command.prune:
        class: Dtc\QueueBundle\Command\PruneCommand
        tags:
            - { name: console.command }

    dtc_queue.command.reset:
        class: Dtc\QueueBundle\Command\ResetCommand
        tags:
            - { name: console.command }

    dtc_queue.command.run:
        class: Dtc\QueueBundle\Command\RunCommand
        tags:
            - { name: console.command }
