language: php
sudo: false
php:
  - 5.6
  - 7.0
  - 7.1

services: mongodb
sudo: required

before_script:
  - composer self-update
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then extension="mongo"; echo "yes" | pecl install mongo; else extension="mongodb"; pecl install mongodb; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then composer require "alcaeus/mongo-php-adapter" --ignore-platform-reqs; fi
  - composer install
  - composer require pda/pheanstalk
  - composer require php-amqplib/php-amqplib
  - if [[ ${TRAVIS_PHP_VERSION:0:2} != "7.1" ]]; composer require doctrine/mongodb-odm 1.1.5; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7.1" ]]; composer require doctrine/mongodb-odm dev-master; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} != "7.1" ]]; composer require doctrine/orm 2.5; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7.1" ]]; composer require doctrine/orm dev-master; fi

script: bin/phpunit --coverage-text

notifications:
  email:
    - mmucklo@gmail.com
